$(".title1").on('click',function(){
  $(this).parent().parent().find('.body1').slideToggle();
});
$(".title2").on('click',function(){
  $(this).parent().parent().find('.body2').slideToggle();
});
$(".title3").on('click',function(){
  $(this).parent().parent().find('.body3').slideToggle();
});
$(".title4").on('click',function(){
  $(this).parent().parent().find('.body4').slideToggle();
});